FROM mcr.microsoft.com/playwright:v1.36.0-jammy

#USER root

# Set root password to something known, cause it will be needed when installing playwright dependencies
#RUN passwd r00t

USER pwuser
WORKDIR /home/pwuser